language: php

php:
  - 5.5

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - app/console cache:warmup --env=test --quiet

script:
    - phpunit -c app