<?php

namespace AppBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllPlayersWithDependencies()
    {
        return $this->createQueryBuilder('player')
            ->select('player, team, country')
            ->join('player.team', 'team')
            ->join('team.country', 'country')
            ->getQuery()
            ->getResult();
            ;
    }
}
