<?php

namespace AppBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTeamByCountrySlug($slug)
    {
        return $this->createQueryBuilder('team')
            ->select('team, country')
            ->leftJoin('team.country', 'country')
            ->andWhere('country.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

    public function getTeamByCountrySlugWithDependencies($slug)
    {
        return $this->createQueryBuilder('team')
            ->select('team, country, players, coaches')
            ->leftJoin('team.country', 'country')
            ->leftJoin('team.players', 'players')
            ->leftJoin('team.coaches', 'coaches')
            ->andWhere('country.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery()
            ->getOneOrNullResult()
            ;
    }

    public function getAllTeamsWithCountry()
    {
        return $this->createQueryBuilder('team')
            ->select('team, country')
            ->leftJoin('team.country', 'country')
            ->getQuery()
            ->getResult()
            ;
    }

}
