<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAllUsersWithDependenciesQuery()
    {
        return $this->createQueryBuilder('user')
             ->select('user, team, country')
             ->join('user.team', 'team')
             ->join('team.country', 'country')
             ->getQuery()
             //->getResult();
             ;
    }

    public function getAllUsersWithPagination( $limit=10, $page=1 )
    {
        $offset = ($page-1)*$limit;

        return $this->createQueryBuilder('user')
            ->select('user')
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->getQuery()
            ->getResult();
            ;
    }

    public function getCountAllUsers()
    {
        return $this->createQueryBuilder('user')
            ->select('count(user.id)')
            ->getQuery()
            ->getSingleScalarResult()
        ;
    }
}
