# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    faker.provider.custom:
        class: AppBundle\DataFixtures\Faker\Provider\CustomProvider
        tags: [ { name: hautelook_alice.faker.provider } ]

