<?php

namespace AppBundle\Entity;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGamesByTeam(Team $team)
    {
        return $this->createQueryBuilder('game')
            ->Where('game.team1 = :teamId')
            ->orWhere('game.team2  = :teamId')
            ->setParameter('teamId', $team->getId())
            ->getQuery()
            ->execute()
            ;
    }
}
